# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenEating' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenEating
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Google'
  pod 'GoogleSignIn'
  pod 'FirebaseUI/Facebook'

end
